name: Cron
run-name: Cron
on:
  schedule:
    - cron: '0 4 * * *'
concurrency:
  group: cron
  cancel-in-progress: true
jobs:
  cron:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript-typescript']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: github/codeql-action/init@v3
        with:
          languages: ${{matrix.language}}
      - name: Build
        uses: github/codeql-action/autobuild@v3
      - name: Analysis
        uses: github/codeql-action/analyze@v3
